DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    PRIMARY KEY (id),
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    name    VARCHAR(255)                                           NOT NULL,
    surname VARCHAR(255)                                           NOT NULL
);