DROP TABLE IF EXISTS grocery_list_items;
DROP TABLE IF EXISTS grocery_lists;
DROP TABLE IF EXISTS grocery_items;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    PRIMARY KEY (id),
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    surname VARCHAR(255)                            NOT NULL
);

CREATE TABLE IF NOT EXISTS grocery_items (
    PRIMARY KEY (id),
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 7) NOT NULL,
    name VARCHAR(255)                                           NOT NULL,
         UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS grocery_lists (
    PRIMARY KEY (id),
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS grocery_list_items (
    PRIMARY KEY (grocery_list_id, grocery_item_id),
    grocery_list_id BIGINT NOT NULL,
    grocery_item_id BIGINT NOT NULL,
                    FOREIGN KEY (grocery_list_id) REFERENCES grocery_lists(id) ON DELETE CASCADE,
                    FOREIGN KEY (grocery_item_id) REFERENCES grocery_items(id) ON DELETE CASCADE
);