DROP TABLE IF EXISTS list_item;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS list;
DROP TABLE IF EXISTS author;

CREATE TABLE IF NOT EXISTS author (
    PRIMARY KEY (id),
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    surname VARCHAR(255)                            NOT NULL
);

CREATE TABLE IF NOT EXISTS list (
    PRIMARY KEY (id),
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author_id BIGINT                                  NOT NULL,
              FOREIGN KEY (author_id) REFERENCES author(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS item (
    PRIMARY KEY (id),
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 7) NOT NULL,
    name VARCHAR(255)                                           NOT NULL,
         UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS list_item (
    PRIMARY KEY (list_id, item_id),
    list_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
            FOREIGN KEY (list_id) REFERENCES list(id) ON DELETE CASCADE,
            FOREIGN KEY (item_id) REFERENCES item(id) ON DELETE CASCADE
);